#!/usr/bin/env bash
#displays "To infinity and beyond" indefinetly

function invincible(){
	echo "I am invincible!!!"
}

trap invincible SIGTERM
while true;do
	echo "To infinity and beyond"
	sleep 2
done
